### ISSUE TITLE
OAuth authentication system

### ISSUE THREAD

**Issue by bdomingues** [bdomingues/ua-digitalsignage#14]
~~- A basic login/password authentication system blueprint, using a sqlite database.~~
~~- Should be implemented in a way that other backend pages can simply add a decorator in order to require user login~~

- Implement an authentication system using UA's OAuth service
- Permissions are given based on the user email
- The decorator requirement still applies
- Integration with SQLAlchemy

**Comment by dgomes** [comment]
skip it...

https://identity.ua.pt/oauth/

**Comment by bdomingues** [comment]
Changed requirements
