### ISSUE TITLE
Distinguish between the types of content and add HTML support

### ISSUE THREAD

**Issue by bdomingues** [bdomingues/ua-digitalsignage#21]
As an improvement on your last iteration, you should now extract the type of content from the json response itself instead of hardocoding it in the app.
The component that renders the text, should also be able to validate and interpret HTML tags and render them accordingly.

**Comment by bdomingues** [comment]
Added @Carlos-Tiago  as an asignee as well. Your web app should also distinguish different types of content from a single endpoint. HTML support should be trivial :)

Use http://mockable.io/ to generate mocks to fit your needs.

**Comment by Carlos-Tiago** [comment]
Commit was delayed in order to slightly improve the structure of the code and preapre it to suit the "final format" of the json input.
