### ISSUE TITLE
OAuth API blocking issues?

### ISSUE THREAD

**Issue by bdomingues** [bdomingues/ua-digitalsignage#22]
I've finally managed to get an access token from idp, however, after some tweaks, the same code is giving me the errors again.

The returned error claims "Invalid Signature" which was the same problem I've been having until earlier today. I though this was due to the signature generation process, but, apparently, the same error is sent when the client key isn't valid (confusing?)

I frequently change the callback url on the application settings due to tests. Does the application need re-approval everytime this happens? That could be a reason why I've been having so many issues.
If not, is there some sort of protection system when you send invalid requests and block you for a couple of hours?

The code worked fine a couple of hours ago and after talking with Diogo Ferreira and Leonardo Oliveira from makerlab, they also used the same method that I am using.

**Comment by dgomes** [comment]
I have no clue... and no access to the source code... only to the database that approves apps :(

And no ones maintains the api anymore :(

**Comment by bdomingues** [comment]
it's alive :)

![alive](https://user-images.githubusercontent.com/15131832/36948169-73b567a6-1fce-11e8-999d-402f033f4bf3.png)
