### ISSUE TITLE
Implement the fullscreen layout and read content from a new structure

### ISSUE THREAD

**Issue by bdomingues** [bdomingues/ua-digitalsignage#40]
- You should implement the fullscreen layout. It only has 1 zone (zone0)
- It should now read the screen content from the proper structure

You can use the following mock point 
http://demo7443497.mockable.io/screen/

Create your own mockpoint to use other types of contents (image,text/html).

**Comment by bdomingues** [comment]
Note: Reading the first video  is enough at this stage. Queuing multiple videos is out of the scope of your issue.

**Comment by jpribeiro7** [comment]
What if it's a different content (an image and a video for example)? Should we set a default display time or is it a problem to deal with later?

**Comment by bdomingues** [comment]
You can setup a default timer or just add a time field to your mock endpoint. Multiple content can be left out of this issue and deal with that in a different one.
