### ISSUE TITLE
Displaying content for a set amount of time

### ISSUE THREAD

**Issue by Carlos-Tiago** [bdomingues/ua-digitalsignage#58]
As for this moment, there is a Json object being fethed from a fix URL.
It's content is displayed as we iterate trough its "inner objects".

**Current situation**: all the content is displayed simultaneaously  

**Objective**:  display it separately, 1 at a time, for a set `duration` (which is defined in their composition), possibly simulating a `sleep()` behaviour after each iteration so it doesn't move to the next one until the duration is complete.

`setTimeout() ` was until now my best bet,  but I couldn't figure how to implement it inside the maping to fulfil the objective. 

EDIT:
After all the made tries, here are the main conclusions about this issue: 
`setTimeout()` does not work on:
- components  
-  return() method 
-  array.prototype.map()` method

Also, as a last resort the `display components` be converted to functions, however it would be of no use as:
In order for the functionality to be scalable to more zones and the necessary pairing between **duration** and the **URL**, the possible solution of storing the content in an array and then iterating trough it while calling the display functions wasn't viable.

Any sugestions are most welcome.

**Comment by bdomingues** [comment]
Example of switching between an array of images with a fixed duration of 2 seconds

https://jsfiddle.net/j66hgkq7/2/
